export const newsApi = [
  {
    uri: "8246251440",
    lang: "eng",
    isDuplicate: false,
    date: "2024-07-27",
    time: "13:50:49",
    dateTime: "2024-07-27T13:50:49Z",
    dateTimePub: "2024-07-27T13:49:10Z",
    dataType: "news",
    sim: 0,
    url: "https://www.thestar.com.my/aseanplus/aseanplus-news/2024/07/27/more-than-family-affairs",
    title: "More than family affairs",
    body: "JAKARTA: Indonesia is going through a limited rather than total political transition this year. Some will resent that, others will applaud it, but nobody can deny it.\n\nThe handover of power from President Joko \"Jokowi\" Widodo to president-elect Prabowo Subianto is shaping up to be a smooth, gradual affair, with lots of continuity in policies and people between the incumbent administration and its successor.\n\nThat has been obvious since well before Jokowi last week appointed to his cabinet two new deputy ministers that have close ties to Prabowo.\n\nAfter all, the President's own son is to be the next vice president.\n\nHence, the market reaction was muted when Jokowi swore in Prabowo's nephew Thomas Djiwandono as deputy finance minister and Prabowo's long-time aide Sudaryono and fellow Gerindra Party executive as deputy agriculture minister at the Presidential Palace on July 18.\n\nThe Indonesia Stock Exchange (IDX) Composite index did better than many other stock markets in the region following the appointments, and while the rupiah decreased slightly against the United States dollar, so did other emerging market currencies that day.\n\nThomas also served as Prabowo's advisor on economic policy and has now been installed under incumbent Finance Minister Sri Mulyani Indrawati with the explicit goal of helping formulate the 2025 state budget plan.\n\nWhat is more, he is set to retain his new position in the incoming administration.\n\nAll of that conveys a notion of policy continuity, which will be a message well received by financial markets amid some concerns that fiscal discipline could fall victim to Prabowo's big spending plans.\n\nWhile the ministerial appointments aim to communicate stability, critics may view them as nepotism.\n\nThat is not a good look for an administration that has not even entered office, so Prabowo and his team must put up a conscious effort to prove that those appointments, and any others, are based on merit.\n\nFormally, there is nothing wrong with an elected president placing trusted individuals in key positions.\n\nTrust is a crucial political currency that no ministerial cabinet could function without.\n\nBut public confidence in the government is no less important than loyalty within the administration, and that kind of political trust must be earned through action that is seen to serve the nation as a whole.\n\nMany countries have family ties in politics, including the United States with the Clintons, the Bushes and more, and they all are under heightened scrutiny to prove that their policies are not family affairs.\n\nAny underperformance must result in demotion or dismissal with no hard feelings.\n\nWhile investors may be unconcerned about the recent appointments, that would quickly change should there be any impression that professionalism is yielding to nepotism.\n\nMoreover, given that the future administration is already working on policymaking, it will be expected to hit the ground running come Oct. 20, when Prabowo to be sworn in as president.\n\nElsewhere, it is customary to give new rulers of the land 100 days after assuming office to prove themselves before being subject to harsher public judgement.\n\nFor instance, in the United Kingdom, a general election was held earlier this month and the new prime minister started work the very next day.\n\nNo such grace period is warranted in Indonesia, where the transition takes the better part of a year, affording an incoming administration months to prepare.\n\nAnd given the active coordination with the incumbents, Prabowo's team in particular should be held to a higher standard.\n\nIndonesian political parties have no clearly defined platforms that allow for straightforward categorization into paradigms such as pro-labor versus pro-employer or interventionist versus isolationist foreign policy.\n\nThey are built around personalities rather than ideologies, and administrations usually seek backing from a motley coalition, further blurring the lines.\n\nGovernments therefore need to be appraised based on their success in key policy deliverables, and that includes a lot more than economic growth.\n\nWe will be watching closely, Pak Prabowo. - The Jakarta Post/ANN",
    source: {
      uri: "thestar.com.my",
      dataType: "news",
      title: "The Star ",
    },
    authors: [],
    image:
      "https://apicms.thestar.com.my/uploads/images/2024/07/27/2826285.jpg",
    eventUri: null,
    sentiment: 0.1294117647058823,
    wgt: 459784249,
    relevance: 54,
  },
  {
    uri: "8246251440",
    lang: "eng",
    isDuplicate: false,
    date: "2024-07-27",
    time: "13:50:49",
    dateTime: "2024-07-27T13:50:49Z",
    dateTimePub: "2024-07-27T13:49:10Z",
    dataType: "news",
    sim: 0,
    url: "https://www.thestar.com.my/aseanplus/aseanplus-news/2024/07/27/more-than-family-affairs",
    title: "More than family affairs",
    body: "JAKARTA: Indonesia is going through a limited rather than total political transition this year. Some will resent that, others will applaud it, but nobody can deny it.\n\nThe handover of power from President Joko \"Jokowi\" Widodo to president-elect Prabowo Subianto is shaping up to be a smooth, gradual affair, with lots of continuity in policies and people between the incumbent administration and its successor.\n\nThat has been obvious since well before Jokowi last week appointed to his cabinet two new deputy ministers that have close ties to Prabowo.\n\nAfter all, the President's own son is to be the next vice president.\n\nHence, the market reaction was muted when Jokowi swore in Prabowo's nephew Thomas Djiwandono as deputy finance minister and Prabowo's long-time aide Sudaryono and fellow Gerindra Party executive as deputy agriculture minister at the Presidential Palace on July 18.\n\nThe Indonesia Stock Exchange (IDX) Composite index did better than many other stock markets in the region following the appointments, and while the rupiah decreased slightly against the United States dollar, so did other emerging market currencies that day.\n\nThomas also served as Prabowo's advisor on economic policy and has now been installed under incumbent Finance Minister Sri Mulyani Indrawati with the explicit goal of helping formulate the 2025 state budget plan.\n\nWhat is more, he is set to retain his new position in the incoming administration.\n\nAll of that conveys a notion of policy continuity, which will be a message well received by financial markets amid some concerns that fiscal discipline could fall victim to Prabowo's big spending plans.\n\nWhile the ministerial appointments aim to communicate stability, critics may view them as nepotism.\n\nThat is not a good look for an administration that has not even entered office, so Prabowo and his team must put up a conscious effort to prove that those appointments, and any others, are based on merit.\n\nFormally, there is nothing wrong with an elected president placing trusted individuals in key positions.\n\nTrust is a crucial political currency that no ministerial cabinet could function without.\n\nBut public confidence in the government is no less important than loyalty within the administration, and that kind of political trust must be earned through action that is seen to serve the nation as a whole.\n\nMany countries have family ties in politics, including the United States with the Clintons, the Bushes and more, and they all are under heightened scrutiny to prove that their policies are not family affairs.\n\nAny underperformance must result in demotion or dismissal with no hard feelings.\n\nWhile investors may be unconcerned about the recent appointments, that would quickly change should there be any impression that professionalism is yielding to nepotism.\n\nMoreover, given that the future administration is already working on policymaking, it will be expected to hit the ground running come Oct. 20, when Prabowo to be sworn in as president.\n\nElsewhere, it is customary to give new rulers of the land 100 days after assuming office to prove themselves before being subject to harsher public judgement.\n\nFor instance, in the United Kingdom, a general election was held earlier this month and the new prime minister started work the very next day.\n\nNo such grace period is warranted in Indonesia, where the transition takes the better part of a year, affording an incoming administration months to prepare.\n\nAnd given the active coordination with the incumbents, Prabowo's team in particular should be held to a higher standard.\n\nIndonesian political parties have no clearly defined platforms that allow for straightforward categorization into paradigms such as pro-labor versus pro-employer or interventionist versus isolationist foreign policy.\n\nThey are built around personalities rather than ideologies, and administrations usually seek backing from a motley coalition, further blurring the lines.\n\nGovernments therefore need to be appraised based on their success in key policy deliverables, and that includes a lot more than economic growth.\n\nWe will be watching closely, Pak Prabowo. - The Jakarta Post/ANN",
    source: {
      uri: "thestar.com.my",
      dataType: "news",
      title: "The Star ",
    },
    authors: [],
    image:
      "https://apicms.thestar.com.my/uploads/images/2024/07/27/2826285.jpg",
    eventUri: null,
    sentiment: 0.1294117647058823,
    wgt: 459784249,
    relevance: 54,
  },
  {
    uri: "8246251440",
    lang: "eng",
    isDuplicate: false,
    date: "2024-07-27",
    time: "13:50:49",
    dateTime: "2024-07-27T13:50:49Z",
    dateTimePub: "2024-07-27T13:49:10Z",
    dataType: "news",
    sim: 0,
    url: "https://www.thestar.com.my/aseanplus/aseanplus-news/2024/07/27/more-than-family-affairs",
    title: "More than family affairs",
    body: "JAKARTA: Indonesia is going through a limited rather than total political transition this year. Some will resent that, others will applaud it, but nobody can deny it.\n\nThe handover of power from President Joko \"Jokowi\" Widodo to president-elect Prabowo Subianto is shaping up to be a smooth, gradual affair, with lots of continuity in policies and people between the incumbent administration and its successor.\n\nThat has been obvious since well before Jokowi last week appointed to his cabinet two new deputy ministers that have close ties to Prabowo.\n\nAfter all, the President's own son is to be the next vice president.\n\nHence, the market reaction was muted when Jokowi swore in Prabowo's nephew Thomas Djiwandono as deputy finance minister and Prabowo's long-time aide Sudaryono and fellow Gerindra Party executive as deputy agriculture minister at the Presidential Palace on July 18.\n\nThe Indonesia Stock Exchange (IDX) Composite index did better than many other stock markets in the region following the appointments, and while the rupiah decreased slightly against the United States dollar, so did other emerging market currencies that day.\n\nThomas also served as Prabowo's advisor on economic policy and has now been installed under incumbent Finance Minister Sri Mulyani Indrawati with the explicit goal of helping formulate the 2025 state budget plan.\n\nWhat is more, he is set to retain his new position in the incoming administration.\n\nAll of that conveys a notion of policy continuity, which will be a message well received by financial markets amid some concerns that fiscal discipline could fall victim to Prabowo's big spending plans.\n\nWhile the ministerial appointments aim to communicate stability, critics may view them as nepotism.\n\nThat is not a good look for an administration that has not even entered office, so Prabowo and his team must put up a conscious effort to prove that those appointments, and any others, are based on merit.\n\nFormally, there is nothing wrong with an elected president placing trusted individuals in key positions.\n\nTrust is a crucial political currency that no ministerial cabinet could function without.\n\nBut public confidence in the government is no less important than loyalty within the administration, and that kind of political trust must be earned through action that is seen to serve the nation as a whole.\n\nMany countries have family ties in politics, including the United States with the Clintons, the Bushes and more, and they all are under heightened scrutiny to prove that their policies are not family affairs.\n\nAny underperformance must result in demotion or dismissal with no hard feelings.\n\nWhile investors may be unconcerned about the recent appointments, that would quickly change should there be any impression that professionalism is yielding to nepotism.\n\nMoreover, given that the future administration is already working on policymaking, it will be expected to hit the ground running come Oct. 20, when Prabowo to be sworn in as president.\n\nElsewhere, it is customary to give new rulers of the land 100 days after assuming office to prove themselves before being subject to harsher public judgement.\n\nFor instance, in the United Kingdom, a general election was held earlier this month and the new prime minister started work the very next day.\n\nNo such grace period is warranted in Indonesia, where the transition takes the better part of a year, affording an incoming administration months to prepare.\n\nAnd given the active coordination with the incumbents, Prabowo's team in particular should be held to a higher standard.\n\nIndonesian political parties have no clearly defined platforms that allow for straightforward categorization into paradigms such as pro-labor versus pro-employer or interventionist versus isolationist foreign policy.\n\nThey are built around personalities rather than ideologies, and administrations usually seek backing from a motley coalition, further blurring the lines.\n\nGovernments therefore need to be appraised based on their success in key policy deliverables, and that includes a lot more than economic growth.\n\nWe will be watching closely, Pak Prabowo. - The Jakarta Post/ANN",
    source: {
      uri: "thestar.com.my",
      dataType: "news",
      title: "The Star ",
    },
    authors: [],
    image:
      "https://apicms.thestar.com.my/uploads/images/2024/07/27/2826285.jpg",
    eventUri: null,
    sentiment: 0.1294117647058823,
    wgt: 459784249,
    relevance: 54,
  },
];
